services:
  nmopti:
    image: slicer/slicer-base:5.6.2
    container_name: ai4radmed-nmopti
    command: tail -f /dev/null
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - /home/ben/projects/ai4radmed/extensions/nmopti:/app
    networks:
      - ai4radmed
    restart: unless-stopped

networks:
  ai4radmed:
    external: true
    name: ai4radmed
