####################################
# 파일명: config/ldap.yml
# 목적: LDAP 컨테이너 설정
#####################################

env_vars:
  LDAP_ORGANISATION: "${LDAP_ORGANISATION}"
  LDAP_DOMAIN: "${LDAP_DOMAIN}"
  LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
  LDAP_CONFIG_PASSWORD: "${LDAP_CONFIG_PASSWORD}"
  
  # Resource Limits
  LDAP_MEM_LIMIT: "256m"
  LDAP_ADMIN_MEM_LIMIT: "128m"
