# ModSecurity Recommended Configuration

# -- Rule Engine --
SecRuleEngine On
SecRequestBodyAccess On

# -- Audit Log --
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogFormat JSON
SecAuditLogType Serial
# [Fix] Nginx Read-Only FS Issue: Log to Stderr
SecAuditLog /dev/stderr

# -- Misc --
SecDebugLog /dev/stderr
SecDebugLogLevel 0
SecResponseBodyAccess Off
